plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
}

android {
    defaultConfig {
        compileSdk 37
        applicationId "com.egoiapp.egoipushlibraryandroid"
        minSdkVersion 23
        targetSdkVersion 37
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'com.egoiapp.egoipushlibraryandroid'
}

dependencies {

    implementation "androidx.core:core-ktx:1.19.0"
    implementation "androidx.appcompat:appcompat:1.7.1"
    implementation "androidx.constraintlayout:constraintlayout:2.2.1"
    implementation "androidx.work:work-runtime-ktx:2.11.2"
    implementation "com.google.android.material:material:1.14.0"
    implementation "com.google.firebase:firebase-messaging:25.1.0"
    implementation 'com.egoiapp.egoipushlibrary:egoipushlibrary:4.2.0'
//    implementation project(':EgoiPushLibrary')
}